# Generated by Django 6.0 on 2025-12-15 12:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.svg', null=True, upload_to=base.models.user_avatar_path),
        ),
    ]
