# Generated by Django 6.0 on 2025-12-15 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='room_qr_codes/'),
        ),
        migrations.AddField(
            model_name='room',
            name='qr_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
