# Generated by Django 6.0 on 2025-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_link_room_qr_code_room_qr_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
