# Generated by Django 6.0 on 2025-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
